# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2224afeb97b20d50e3c2ff691a0784375cf71d3ce551de973f598fac5d39c1fdeafa661ed794f3c9f059ba8e0e516b65f0aa7595ab24a4b595623c36bde58c1f

test:
  secret_key_base: 85ca5225271a4a3ca3e08aa788a9dd59a9ced3d7f87bf7454f4d8442e227654d87398b3bf620036b22e72233a63c9960a21d80d23ea40a4371f7018e9436c63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
